"""add account lockout fields to users

Revision ID: 2171eec48fb9
Revises: bc5771a53c06
Create Date: 2026-08-28 14:08:01.875110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2171eec48fb9'
down_revision: Union[str, Sequence[str], None] = 'bc5771a53c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ВАЖНО (правка вручную после автогенерации): у существующих строк
    # users уже есть данные, а failed_login_attempts объявлена NOT NULL.
    # Без server_default ALTER TABLE упал бы на Postgres с ошибкой
    # "column contains null values". server_default='0' здесь — это
    # значение НА УРОВНЕ БД для уже существующих строк при накатывании
    # миграции; Python-модель (app/models.py) использует свой ORM-default
    # только для новых INSERT и его одного недостаточно для ALTER TABLE
    # на непустой таблице.
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
