"""add multitrack track and clip tables

Revision ID: 412aa37515c0
Revises: 06bfedefbefa
Create Date: 2026-08-28 18:53:34.339066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412aa37515c0'
down_revision: Union[str, Sequence[str], None] = '06bfedefbefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('moment_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('VIDEO', 'AUDIO', name='tracktype'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moment_id'], ['moments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('track_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('source_duration', sa.Float(), nullable=True),
    sa.Column('position_start', sa.Float(), nullable=False),
    sa.Column('position_end', sa.Float(), nullable=False),
    sa.Column('trim_start', sa.Float(), nullable=False),
    sa.Column('trim_end', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('pip_x', sa.Float(), nullable=False),
    sa.Column('pip_y', sa.Float(), nullable=False),
    sa.Column('pip_width', sa.Float(), nullable=False),
    sa.Column('pip_height', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clips')
    op.drop_table('tracks')
    # ### end Alembic commands ###
