"""add banner audio overlay fields to moments

Revision ID: bb81b5c2a6a1
Revises: 06bfedefbefa
Create Date: 2026-08-28 15:21:44.611103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb81b5c2a6a1'
down_revision: Union[str, Sequence[str], None] = '06bfedefbefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ВАЖНО (правка вручную после автогенерации): audio_volume объявлена
    # NOT NULL — без server_default ALTER TABLE упал бы на Postgres с
    # существующими строками ("column contains null values"), тот же
    # случай, что уже был с failed_login_attempts.
    with op.batch_alter_table('moments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_path', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('audio_duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('audio_trim_start', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('audio_trim_end', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('audio_volume', sa.Float(), nullable=False, server_default='1.0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moments', schema=None) as batch_op:
        batch_op.drop_column('audio_volume')
        batch_op.drop_column('audio_trim_end')
        batch_op.drop_column('audio_trim_start')
        batch_op.drop_column('audio_duration')
        batch_op.drop_column('audio_path')

    # ### end Alembic commands ###
