"""add is_admin field to users

Revision ID: bd03f24426b4
Revises: 7e1df80cd75a
Create Date: 2026-09-01 18:30:23.457930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd03f24426b4'
down_revision: Union[str, Sequence[str], None] = '7e1df80cd75a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ВАЖНО (правка вручную после автогенерации, как и с failed_login_attempts
    # в 2171eec48fb9): таблица users уже может содержать реальные строки,
    # а is_admin объявлена NOT NULL — без server_default ALTER TABLE упал бы
    # на Postgres с "column contains null values". server_default='0' —
    # значение на уровне БД для уже существующих строк, отдельно от
    # ORM-default в app/models.py (тот применяется только к новым INSERT).
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
